### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Van4712** [aws-samples/aws-mobile-android-notes-tutorial#7]
I keep getting Execution failed for task:app:mergeDebugResources

**Comment by adrianhall** [comment]
Unfortunately, I need a little more information to go on here.  What precisely did you do?  What is your environment like? (Both operating system and Android Studio version)?  What API levels do you have installed? Does the Messages window say anything?

**Comment by BrianJerardi** [comment]
I am getting the same error (see below) when attempting to build the project after a fresh clone of the repo.  
I'm using Windows 10, Android Studio 3.0.1

Error:Execution failed for task ':app:mergeDebugResources'.
> There were multiple failures while executing work items
   > A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
      > Error while processing C:\Users\-\AndroidStudioProjects\aws-mobile-android-notes-tutorial\app\src\main\res\drawable\ic_add_black_24dp.xml : Can't process attribute android:fillColor="@android:color/darker_gray": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
   > A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
      > Error while processing C:\Users\-\AndroidStudioProjects\aws-mobile-android-notes-tutorial\app\src\main\res\drawable\ic_add_black_24dp.xml : Can't process attribute android:fillColor="@android:color/darker_gray": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
   > A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
      > Error while processing C:\Users\-\AndroidStudioProjects\aws-mobile-android-notes-tutorial\app\src\main\res\drawable\ic_add_black_24dp.xml : Can't process attribute android:fillColor="@android:color/darker_gray": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
   > A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
      > Error while processing C:\Users\-\AndroidStudioProjects\aws-mobile-android-notes-tutorial\app\src\main\res\drawable\ic_add_black_24dp.xml : Can't process attribute android:fillColor="@android:color/darker_gray": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
   > A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
      > Error while processing C:\Users\-\AndroidStudioProjects\aws-mobile-android-notes-tutorial\app\src\main\res\drawable\ic_add_black_24dp.xml : Can't process attribute android:fillColor="@android:color/darker_gray": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
   > A failure occurred while executing com.android.build.gradle.tasks.MergeResources$FileGenerationWorkAction
      > Error while processing C:\Users\-\AndroidStudioProjects\aws-mobile-android-notes-tutorial\app\src\main\res\drawable\ic_add_black_24dp.xml : Can't process attribute android:fillColor="@android:color/darker_gray": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.

**Comment by adrianhall** [comment]
Fixed with PR #8 - thank you for the contribution, @BrianJerardi
